site_name: MrChike
site_url: https://mrchike.github.io/portfolio/
repo_name: MrChike/portfolio
repo_url: https://github.com/MrChike/portfolio
theme:
  name: material
  # Logo can be updated @ docs/overrides/partials/logo.html
  favicon: docs/assets/images/favicon.ico
  custom_dir: docs/overrides
  icon:
    repo: octicons/mark-github-24
    admonition:
      note: material/notebook-heart-outline
  font:
    text: Ubuntu Mono
  features:
    - announce.dismiss
    - content.code.copy
    - toc.integrate
    - navigation.tabs
    - navigation.top
    - navigation.footer
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: blue grey
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: deep orange
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  markdown_extensions:
    - material.extensions.preview:
        configurations:
          - targets:
              include:
                - docs/*

nav:
  - index.md
  - projects.md
  - contributions.md
  - certifications.md
  - articles.md

extra:
  social:
    - icon: fontawesome/brands/dev
      link: https://dev.to/mrchike
      name: My DEV Profile
    - icon: material/linkedin
      link: https://www.linkedin.com/in/chikeegonu/
      name: My LinkedIn Profile
    - icon: fontawesome/brands/github
      link: https://github.com/MrChike
      name: My Github Profile
    - icon: simple/leetcode
      link: https://leetcode.com/mrchike
      name: My LeetCode Profile
    - icon: fontawesome/brands/kaggle
      link: https://www.kaggle.com/chikeegonu
      name: My Kaggle Profile

extra_css:
  - assets/stylesheets/extra.css

extra_javascript:
  - assets/javascripts/extra.js
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/js/all.min.js
  - https://cdn.jsdelivr.net/npm/@primer/octicons@19.6.0/build/build.js

copyright: Copyright ©️ 2025 - Infinityyyyy & Beyond 🚀 - Chike Egonu